<script src="scripts/jquery.js"></script>
<script src="scripts/maskedinput.js"></script>
<script src="scripts/slider.js"></script>
<script src="scripts/header.js"></script>
<script src="scripts/time.js"></script>
<script src="scripts/teachers.js"></script>
<script src="scripts/gallery.js"></script>
<script src="scripts/addresses.js"></script>
<script src="scripts/videos.js"></script>
<script src="scripts/blog.js"></script>
<script src="scripts/reviews.js"></script>
<script src="scripts/bonuses.js"></script>
<script src="scripts/register.js"></script>
<script src="scripts/events.js"></script>
<script src="scripts/mango.js"></script>
<script src="scripts/yandex_metrika.js"></script>
<script src="scripts/vk.js"></script>
<script src="https://vk.com/js/api/openapi.js?159"></script>
<script src="scripts/vk_widget.js" defer></script>
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-146792432-1"></script>
